// Pure data functions for the generation timeline scrubber.
//
// Two responsibilities:
//   1. Bucketize a set of responses into N equal-width time slices, with
//      cumulative sentiment counts per slice — feeds the sparkline.
//   2. Binary-search the playhead into a sorted response list — drives the
//      "current response" callouts and the table-sync filter at scrub time.
//
// Both run on every scrub event for large datasets (5,000 responses), so
// they avoid allocations in the hot path: bucketize iterates once, the
// playhead search is O(log n).

import type { GeneratedResponse } from "@/lib/generation/response-types";
import type { Persona, SentimentArchetype } from "@/lib/generation/persona-types";

/** Output of bucketizeResponses — one entry per time slice. */
export interface SentimentBucket {
  /** Inclusive lower bound of the bucket window (ms since epoch). */
  start: number;
  /** Exclusive upper bound. The last bucket uses `<=` instead of `<` to
   *  catch the final response which sits exactly at endMs. */
  end: number;
  /** Cumulative counts as of the bucket's end — i.e. promoters who have
   *  been generated by this point in the timeline, not just within this
   *  bucket. The sparkline plots cumulative values. */
  cumPromoter: number;
  cumPassive: number;
  cumDetractor: number;
  /** Total cumulative = cumPromoter + cumPassive + cumDetractor. Pre-summed
   *  so the chart layer doesn't recompute it per render. */
  cumTotal: number;
}

/**
 * Slice the [startMs, endMs] window into `bucketCount` equal-width buckets
 * and compute cumulative sentiment counts at each bucket boundary.
 *
 * Responses are assumed sorted ascending by `generatedAt`; pass the same
 * sorted array used elsewhere to avoid resorting.
 *
 * Unknown sentiment (persona missing from the lookup map) is counted as
 * passive — keeps the totals honest without dropping the response.
 */
export function bucketizeResponses(
  sortedResponses: GeneratedResponse[],
  personas: Persona[],
  startMs: number,
  endMs: number,
  bucketCount = 30,
): SentimentBucket[] {
  const personaById = new Map(personas.map((p) => [p.id, p] as const));
  const span = Math.max(1, endMs - startMs); // avoid div-by-zero
  const sliceMs = span / bucketCount;

  const buckets: SentimentBucket[] = new Array(bucketCount);
  let cumP = 0;
  let cumPa = 0;
  let cumD = 0;
  let rIdx = 0;

  for (let i = 0; i < bucketCount; i++) {
    const sliceStart = startMs + i * sliceMs;
    const sliceEnd = i === bucketCount - 1 ? endMs : startMs + (i + 1) * sliceMs;

    // Walk responses whose generatedAt falls in this slice. Responses are
    // sorted, so we just advance rIdx — no per-bucket scan.
    while (rIdx < sortedResponses.length) {
      const r = sortedResponses[rIdx]!;
      const within =
        i === bucketCount - 1 ? r.generatedAt <= sliceEnd : r.generatedAt < sliceEnd;
      if (!within) break;

      const archetype: SentimentArchetype =
        personaById.get(r.personaId)?.sentimentArchetype ?? "passive";
      if (archetype === "promoter") cumP++;
      else if (archetype === "detractor") cumD++;
      else cumPa++;
      rIdx++;
    }

    buckets[i] = {
      start: sliceStart,
      end: sliceEnd,
      cumPromoter: cumP,
      cumPassive: cumPa,
      cumDetractor: cumD,
      cumTotal: cumP + cumPa + cumD,
    };
  }

  return buckets;
}

/**
 * Binary-search for the largest index `i` such that `sorted[i].generatedAt <= playheadMs`.
 * Returns -1 if no response has fired yet by the playhead position.
 *
 * Used both for "which persona is the playhead currently on?" and for the
 * sync-with-table filter (table shows everything up to and including this
 * index).
 */
export function findResponseIndexAtPlayhead(
  sorted: GeneratedResponse[],
  playheadMs: number,
): number {
  if (sorted.length === 0) return -1;
  if (playheadMs < sorted[0]!.generatedAt) return -1;
  if (playheadMs >= sorted[sorted.length - 1]!.generatedAt) return sorted.length - 1;

  let lo = 0;
  let hi = sorted.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >>> 1; // bias high so we converge on the right edge
    if (sorted[mid]!.generatedAt <= playheadMs) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}
